version: "3"

services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft
    volumes:
      - minecraftdata:/data
      - /home/minecraft/plugins:/plugins
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      TYPE: "SPIGOT"
      MEMORY: 2G
      ENABLE_WHITELIST: "FALSE"
      ENFORCE_WHITELIST: "FALSE"
    tty: true
    stdin_open: true
    restart: unless-stopped
volumes:
  minecraftdata:
    external: true
